[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
showSidebarNavigation = false

[server]
headless = true
runOnSave = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = true

[runner]
magicEnabled = false
